# Generated by Django 2.2.5 on 2022-09-25 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='user',
            field=models.OneToOneField(on_delete='cascade', related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
